services:
  db: 
    image: mysql:8.0.32
    container_name: school_manager_db_MB
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school_manager
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: 'always'

  backend: 
    build: backend
    container_name: school_manager_backend
    command: dev
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app:rw
    tty: true
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_NAME: school_manager
      MYSQL_HOST: db
      NODE_ENV: development
      MYSQL_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3333"]
      timeout: 10s
      retries: 5
  frontend: 
    build: frontend
    container_name: school_manager_frontend
    ports:
      - 3000:3000
    command: dev
    volumes:
      - ./frontend:/app:rw
    tty: true
    environment:
      - VITE_BASE_URL=http://localhost:3333
      - VITE_ROUTE_PUT=false
    depends_on:
      backend:
        condition: service_healthy