services:
  db: 
    image: mysql:8.0.32
    container_name: school_manager_db_MB
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school_manager
    ports:
      - 3306:3306
  backend: 
    build: backend
    container_name: school_manager_backend
    ports:
      - 3333:3333
    volumes:
      # - /home/leandro/programacao/avaliacoes/MBPsicologia/backend
      - ./backend:/app/backend:rw
    tty: true
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_NAME: school_manager
      MYSQL_HOST: db
      NODE_ENV: development
      MYSQL_PORT: 3306
    depends_on:
      - db
  frontend: 
    build: frontend
    container_name: school_manager_frontend
    ports:
      - 3000:3000
    command: dev
    volumes:
      - /home/leandro/programacao/avaliacoes/MBPsicologia/frontend
      - ./frontend:/app/frontend:rw
    tty: true
    environment:
      - VITE_BASE_URL=http://localhost:3333
    depends_on:
      - backend